services:
    covex.twig_callback_bridge.twig_extension:
        class: Covex\TwigCallbackBridgeBundle\Twig\Extension
        tags:
            - { name: twig.extension }

    covex.twig_callback.bridge_function:
        class: Covex\TwigCallbackBridgeBundle\Callback\Callback
        arguments:
            - 'function'
        public: false
        abstract: true

    covex.twig_callback.bridge_filter:
        class: Covex\TwigCallbackBridgeBundle\Callback\Callback
        arguments:
            - 'filter'
        public: false
        abstract: true

    covex.twig_callback.bridge_test:
        class: Covex\TwigCallbackBridgeBundle\Callback\Callback
        arguments:
            - 'test'
        public: false
        abstract: true
